import { Page, expect } from "@playwright/test";
import * as path from "path";
import { readFileSync } from "fs";

const ROOT = path.resolve(__dirname, "..");

// Load test keys from .test-keys.json (generated by global-setup)
function loadTestKeys() {
  const keysPath = path.join(ROOT, ".test-keys.json");
  const keys = JSON.parse(readFileSync(keysPath, "utf-8"));
  return {
    privkeyHex: keys.privkeyHex as string,
    pubkeyHex: keys.pubkeyHex as string,
    npub: keys.npub as string,
    nsec: keys.nsec as string,
  };
}

// Lazily loaded crypto modules
let _schnorr: any;
let _sha256: any;
let _hexUtils: any;

async function loadCrypto() {
  if (_schnorr) return;
  _schnorr = require(
    path.join(
      ROOT,
      "node_modules/.pnpm/@noble+secp256k1@1.7.2/node_modules/@noble/secp256k1",
    ),
  ).schnorr;
  _sha256 = require(
    path.join(
      ROOT,
      "node_modules/.pnpm/@noble+hashes@1.3.2/node_modules/@noble/hashes/sha256",
    ),
  ).sha256;
  _hexUtils = require(
    path.join(
      ROOT,
      "node_modules/.pnpm/@noble+hashes@1.3.2/node_modules/@noble/hashes/utils",
    ),
  );
}

function serializeEvent(evt: {
  pubkey: string;
  created_at: number;
  kind: number;
  tags: string[][];
  content: string;
}) {
  return JSON.stringify([
    0,
    evt.pubkey,
    evt.created_at,
    evt.kind,
    evt.tags,
    evt.content,
  ]);
}

function getEventHash(evt: any): string {
  const bytes = _hexUtils.utf8ToBytes(serializeEvent(evt));
  return _hexUtils.bytesToHex(_sha256(bytes));
}

async function signEvent(evt: any): Promise<any> {
  const { privkeyHex } = loadTestKeys();
  await loadCrypto();
  const sk = _hexUtils.hexToBytes(privkeyHex);
  const id = getEventHash(evt);
  const sigBytes = await _schnorr.sign(id, sk);
  return { ...evt, id, sig: _hexUtils.bytesToHex(sigBytes) };
}

/**
 * Injects a NIP-07 compatible window.nostr mock into the browser.
 * Uses the dynamically generated test account's private key to sign events.
 * Also injects window.__TEST_WHITELIST so the app uses the test key's pubkey
 * for relay filtering — bypassing the static config.json whitelist.
 * Must be called before page.goto().
 */
export async function injectNostrExtension(page: Page) {
  const { pubkeyHex, npub } = loadTestKeys();

  await page.exposeFunction("__nostrSign", (evt: any) => signEvent(evt));

  await page.addInitScript(
    ({ pubkey, npubStr }: { pubkey: string; npubStr: string }) => {
      (window as any).nostr = {
        async getPublicKey() {
          return pubkey;
        },
        async signEvent(event: any) {
          return (window as any).__nostrSign({
            kind: event.kind,
            content: event.content,
            tags: event.tags,
            created_at: event.created_at,
            pubkey: event.pubkey,
          });
        },
      };
      // Override the whitelist so the app only shows content from the test key
      (window as any).__TEST_WHITELIST = [pubkey];
      // Pre-populate localStorage so NostrContext auto-restores the user
      localStorage.setItem(
        "nostr_user",
        JSON.stringify({ pubkey, npub: npubStr }),
      );
    },
    { pubkey: pubkeyHex, npubStr: npub },
  );
}

/**
 * Returns the current test keys (useful for tests that need the pubkey/npub).
 */
export function getTestKeys() {
  return loadTestKeys();
}

/**
 * Logs in using the test account via "Use Existing Key" flow.
 * Assumes the login modal is NOT open yet.
 */
export async function loginWithTestAccount(page: Page) {
  const { nsec } = loadTestKeys();
  await page.getByRole("button", { name: /connect nostr/i }).click();
  await expect(page.getByText("Connect with Nostr")).toBeVisible();
  await page.getByRole("button", { name: /use existing key/i }).click();
  await page.getByLabel(/private key or nsec/i).fill(nsec);
  await page.getByRole("button", { name: /^sign in$/i }).click();
  await expect(page.locator("header").getByText(/npub1/)).toBeVisible({
    timeout: 10000,
  });
}
