name: DNS

on:
  push:
    branches: ["master"]
    paths:
      - "terraform/**"

permissions:
  contents: write # Required to update state

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: tf
        uses: hashicorp/setup-terraform@v3
      - run: cd terraform; terraform init

      - id: plan
        run: |
          cd terraform; pwd; ls -lah
          git config --global user.email "pipeline@example.com"
          git config --global user.name "pipeline"
          terraform apply -no-color --var-file=envs/prod.tfvars --var="api_key=${{ secrets.DREAMHOST_KEY }}" --auto-approve
          git add .; git commit -m 'updated state'; git push

      # - run: echo "${{ steps.plan.outputs.stdout }}"
      # - run: echo ${{ steps.plan.outputs.stderr }}
      # - run: echo ${{ steps.plan.outputs.exitcode }}
